### ISSUE TITLE
AJAX with $defer.resolve doesn't work

### ISSUE THREAD

**Issue by SantjagoCorkez** [esvit/ng-table#575] opened 2015-03-20 09:38 UTC
The scope is defined as:
```javascript
        loadData: function($defer, params) {
            if (me.load_data_timeout) {
                $timeout.cancel(me.load_data_timeout);
            }
            me.load_data_timeout = $timeout(function() {
                $scope.loading = true;
                params.total(0);
                $http.post('/url/for/data', {
                    filters: $scope.filters,
                    sorting: params.sorting(),
                    limit: params.count(),
                    skip: params.page()
                }).success(function(data) {
                    $timeout(function() {
                        params.total(data.count);
                        $defer.resolve(data.items);
                    }, 500);
                }).finally(function() {
                    $scope.loading = false;
                });
            }, 2000);
        }
...
        table: new ngTableParams({
            page: 1,
            count: 25,
            sorting: {
                'id': 'desc'
            }
        }, {
            total: 0,
            getData: me.loadData
        }),
```

The first time the `getData` executes (with either filters or not) it fills the table with data as expected; My pagination template has `ng-hide="pages.length == 0"` check so it reflects the amount of data correctly; With any subsequent getData call the request returns another data set (or even empty), the pagination reflects the new items count but the table itself (and it's scope $data parameter) does not update to the result set.

**Comment by SantjagoCorkez** [comment] 2015-03-20 11:00
Forgot to mention: ngTable version is 0.4.3

**Comment by chillyistkult** [comment] 2015-08-03 13:03
Still broken in 0.8.1

**Comment by christianacca** [comment] 2015-08-03 17:07
Hi @chillyistkult,

Without a running example, it's hard to diagnose what the problem is.

I've created a [codepen](http://codepen.io/christianacca/pen/oXJJYY?editors=101) as a starting point for creating a reproduction of the problem you've observed.

Can you **fork the [codepen](http://codepen.io/christianacca/pen/oXJJYY?editors=101) and adapt to demonstrate the issue** you're seeing.

C

**Comment by chillyistkult** [comment] 2015-08-10 12:22
I found the problem. The pagination is not working if a request takes longer then approximately 700 milliseconds. Thats why your codepen works and real world api's don't. It's a problem in your event driven architecture, because $on('ngTableAfterReloadData') gets called before the total value in the promise isset and therefore total is 0.

I will provide a simple codepen simulate this behaviour in the next minutes.

**Comment by ccrowhurstram** [comment] 2015-08-10 12:33
Hi @chillyistkult, try using the latest release to see whether the problem is already.

I've create another [codepen](http://codepen.io/christianacca/pen/rVRpqX?editors=101) that links to the current release (1.0.0-alpha)

**Comment by chillyistkult** [comment] 2015-08-10 12:38
Looks like the current release solves the issue.

**Comment by ccrowhurstram** [comment] 2015-08-10 12:41
Cool. You ok with me closing this issue now?

**Comment by chillyistkult** [comment] 2015-08-10 12:43
Yes thanks for your efforts!

**Comment by christianacca** [comment] 2015-08-10 12:54
Great

**Closed by christianacca** 2015-08-10 12:54 UTC
