### ISSUE TITLE
after upgrade 0.8.0 -> 0.8.1 paging doesn't work

### ISSUE THREAD

**Issue by lichtner** [esvit/ng-table#669] opened 2015-08-06 08:22 UTC
after click on next page rows didn't change. (only index in template is updated), index looks like:
```
{{(tableParams.page() - 1) * tableParams.count() + $index + 1}}
```
on first page are index from 1..10 on second page 11..20 etc. (this is correct behavior)
also after click on next page, params in url didn't change (stay page=1&count=10 on all pages)
no error occurs in chrome console.

after rollback to 0.8.0 everything works again correctly.
controller looks like this (I hope you understand coffee):

```coffeescript
.controller 'ListCtrl', ($scope, $location, $q, $http, ngTableParams) ->
  $scope.tableParams = new ngTableParams(
    angular.extend({
      page: 1 # start page
      count: 10 # counts per page
    }, $location.search())
  ,
    counts: [10, 20, 30, 50, 100]
    filterDelay: 300
    getData: ($defer, params) ->
      $location.search params.url() # put params in url
      apiParams =
        page: params.page()
        count: params.count()
        filter: params.filter()
      $http.get('/api/user', params: apiParams).then (res) ->
        params.total res.data.count
        $defer.resolve res.data.rows
      return
  )
```

it is difficult to isolate error, I hope this helps.

**Comment by christianacca** [comment] 2015-08-06 09:33
https://github.com/esvit/ng-table/commit/7aa4260c8a2882f651af66bfafb271a37569cbaa might have fixed things. I've created another release [0.8.2](https://github.com/esvit/ng-table/releases/tag/v0.8.2), can you test against this to see if it resolves your issue.

**Comment by lichtner** [comment] 2015-08-06 12:48
sorry still doesn't work :( same behavior ...

**Comment by christianacca** [comment] 2015-08-06 14:08
The only thing that I can see that is unusual with the code you posted is this line:

```coffeescript
$location.search params.url() # put params in url
```

Wouldn't that trigger a reload of the entire route, which will cause your page to reload, which in turn will cause a new `NgTableParams` to be created and assigned to `$scope.tableParams`.

Can you explain the motivate for **why you're using this technique of reloading the route whenever the table needs to display a new result**.

Also...

Here's a bit of the inner workings of what happens when `getData` is called - it might help self diagnose the problem.

1. your `getData` function calls `$defer.resolve` supplying the current page worth of items as an array
2. `NgTableParams` assigns the array you've returned to an own property namely `data` (so for example `$scope.tableParams.data` will have the reference to the array)
3. `NgTableParams` publishes an event named `afterReloadData` with this array as one of the args to this event (note: it uses the `ngTableEventsChannel` to publish this event)
4. `ngTableController` (the controller for the `ngTable` directive) subscribes to this event and sets the `$scope.$data` field when the event is fired to the array
5. Your template (typically) has an ng-repeat over the this `$data` array; eg: `<tr ng-repeat="row in $data">`

So for whatever reason it seems that the `$data` array is not being assigned to the current page worth of data. You could try setting a breakpoint in chrome dev tools on the following lines of code to see whether the above code path is being followed in your case:

* [L782](https://github.com/esvit/ng-table/blob/master/dist/ng-table.js#L782): start of the call to `reload`
* [L798](https://github.com/esvit/ng-table/blob/master/dist/ng-table.js#L798): inside the call to `reload`, after your call to `$defer.resolve`
* [L1156](https://github.com/esvit/ng-table/blob/master/dist/ng-table.js#L1156): inside of the `ngTableController` event handler firing in response to the `afterReloadData` is fired by the `reload` function

**Comment by lichtner** [comment] 2015-08-07 11:40
Thanks I resolved it! Sorry I made mistake, I tried to simplified example and I remove something what was important for this bug:

```coffee
getData: ($defer, params) ->
      $location.search params.url() # put params in url
      apiParams =
        page: params.page()
        count: params.count()
        filter: params.filter()
      apiParams.filter.archived = 0   # this was the problem !!!! <------------
      $http.get('/api/user', params: apiParams).then (res) ->
        params.total res.data.count
        $defer.resolve res.data.rows
      return
```

problem was that `apiParams.filter` is only reference and after I tried to add `filter.archived = 0` which is not exists column in dataset. After I comment out this row everything works correctly.

Second solution was copy filter as object: 

```coffee
apiParams =
    page: params.page()
    count: params.count()
    filter: angular.copy(params.filter())
apiParams.filter.archived = 0
```

May be you can detect this and throw some exception in console if somebody tried to add non exist column in filter. It could be very helpful. 

To second question: why I use: `$location.search params.url()`

Common use case:

- I move to page 5
- I edit row in page 5
- after save row I call `$window.history.back()` 
- because I want to go back to page 5 (not first page)

Without saving `page` and `count` in url it returned me to first page of table (I use ui-router). Do you can recommend me better solution (best practice) for this? 

Sorry again for my first mistake.

**Comment by christianacca** [comment] 2015-08-07 17:54
FYI, when you set `apiParams.filter.archived = 0`, internally this triggers a reset of the page. This is to avoid the user seeing an empty page of table data.

In hindsight the fact that the `filter` method returns a *reference* and not a copy of the data is I believe the wrong design - I think this design more often than not causes *unintentional* side affects.

I think this is the root cause of the problem, but I think it's too big and subtle a breaking change to fix now.

OK, so I don't have any real *practical* experience of using the ui-router and nested states. I just wonder whether causing the route to reload *inside of an async promise chain* (`reload` > `getData`) is a good thing to do...

**Closed** 2015-08-08 23:14 UTC
